### ISSUE TITLE
Is it possible to update an injectable, i.e. make it dynamic?

### ISSUE THREAD

**Issue by rodrigomf24** [albertogasparin/react-magnetic-di#35] opened 2020-09-08 23:49 UTC
Hi, I encountered a specific scenario in which I need to make a prop provided by the mocked hook dynamic, here is the code:

```const SelectRoomPageUIStory = (
  passedProps: SelectRoomPageUIProps & { selectResort: ResortComparisonDropdownProps },
) => {
  const [selectedPropertyId, setSelectedPropertyId] = React.useState('2');
  const [selectedCardId, setRoomRateCardId] = React.useState('2');

  const onChange = useCallback(
    (id: any) => {
      setSelectedPropertyId(id);
    },
    [setSelectedPropertyId],
  );

  const useResortControllerDi = injectable(useResortController, () => ({
    apolloResult: {
      loading: false,
    } as ApolloResult,
    uiProps: {
      ...passedProps.selectResort,
      selectedPropertyId,
      onChange: onChange,
    },
  }));

  return (
    <DiProvider use={[useResortControllerDi]}>
      <SelectRoomPageUI
        {...passedProps}
      />
    </DiProvider>
  );
};
```

As you can notice the value of `selectedPropertyId` is dynamic, the reason I ended up needing to mock the hook is because there's a component nested under `SelectRoomPageUI` that consumes from the hook directly(the idea was to avoid prop drilling), thanks to your library I fixed it and the story now renders the list of values being mocked properly on the nested component, but when I trigger the `onChange` method it does update and if I use `useEffect` to watch the `selectedPropertyId` value it reflects it properly on the console but the value returned by `useResortControllerDi` never updates. 

If I'm doing this wrong please feel free to correct me, and thanks again for making this library it saved me a lot of time of r&d.

**Comment by albertogasparin** [comment] 2020-09-11 10:51
I haven't tested it out, but I think the issue is just due to the closure.
If you save `selectedPropertyId` to a ref (so a stable object) and use that internally in the return value of the hook, it should work:

```js

const selectedPropertyIdRef = useRef();
selectedPropertyIdRef.current = selectedPropertyId;

const useResortControllerDi = injectable(useResortController, () => ({
    apolloResult: {
      loading: false,
    } as ApolloResult,
    uiProps: {
      ...passedProps.selectResort,
      selectedPropertyId: selectedPropertyIdRef.current,
      onChange: onChange,
    },
  }));
```

If this does not work can you create a simple code codesandbox so can better help you out? As making `DiProvider` react to `use` values change cannot be done (too many implications).

**Comment by albertogasparin** [comment] 2020-11-20 23:34
Closing for now. If you have more questions do not hesitate to reply

**Closed by albertogasparin** 2020-11-20 23:34 UTC
Labels: question
